driver_names = {
    1: 'Charles Leclerc',
    2: 'Carlos Sainz',
    3: 'Lewis Hamilton',
    4: 'George Russell',
    5: 'Kevin Magnussen',
    6: 'Valtteri Bottas',
    7: 'Esteban Ocon',
    8: 'Yuki Tsunoda',
    9: 'Fernando Alonso',
    10: 'Guanyu Zhou',
    11: 'Mick Schumacher',
    12: 'Lance Stroll',
    13: 'Alexander Albon',
    14: 'Daniel Ricciardo',
    15: 'Lando Norris',
    16: 'Nicholas Latifi',
    17: 'Nico Hulkenberg',
    18: 'Sergio Perez',
    19: 'Max Verstappen',
    20: 'Pierre Gasly',
    21: 'Sebastian Vettel',
    22: 'Nyck De Vries',
    23: 'Logan Sargeant',
    24: 'Oscar Piastri',
    25: 'Liam Lawson',
    26: 'Oliver Bearman',
    27: 'Franco Colapinto',
    28: 'Jack Doohan',
    29: 'Andrea Kimi Antonelli',
    30: 'Gabriel Bortoleto',
    31: 'Isack Hadjar',
    32: 'Kimi Antonelli'
}

driver_ids = {
    'Charles Leclerc': 1,
    'Carlos Sainz': 2,
    'Lewis Hamilton': 3,
    'George Russell': 4,
    'Kevin Magnussen': 5,
    'Valtteri Bottas': 6,
    'Esteban Ocon': 7,
    'Yuki Tsunoda': 8,
    'Fernando Alonso': 9,
    'Guanyu Zhou': 10,
    'Mick Schumacher': 11,
    'Lance Stroll': 12,
    'Alexander Albon': 13,
    'Daniel Ricciardo': 14,
    'Lando Norris': 15,
    'Nicholas Latifi': 16,
    'Nico Hulkenberg': 17,
    'Sergio Perez': 18,
    'Max Verstappen': 19,
    'Pierre Gasly': 20,
    'Sebastian Vettel': 21,
    'Nyck De Vries': 22,
    'Logan Sargeant': 23,
    'Oscar Piastri': 24,
    'Liam Lawson': 25,
    'Oliver Bearman': 26,
    'Franco Colapinto': 27,
    'Jack Doohan': 28,
    'Andrea Kimi Antonelli': 29,
    'Gabriel Bortoleto': 30,
    'Isack Hadjar': 31,
    'Kimi Antonelli': 32
}

track_ids = {
    'Austin': '19',
    'Baku': '8',
    'Barcelona': '6',
    'Budapest': '13',
    'Imola': '4',
    'Jeddah': '2',
    'Le Castellet': '12',
    'Marina Bay': '17',
    'Melbourne': '3',
    'Mexico City': '20',
    'Miami': '5',
    'Monaco': '7',
    'Montreal': '9',
    'Monza': '16',
    'Sakhir': '1',
    'Sao Paulo': '21',
    'Silverstone': '10',
    'Spa-Francorchamps': '14',
    'Spielberg': '11',
    'Suzuka': '18',
    'Yas Island': '22',
    'Zandvoort': '15',
    'Las Vegas': '24',
    'Lusail': '23',
    'Shanghai': '25',
    'Hungary': '10'
}