driver_names = {
    1: 'Charles Leclerc',
    2: 'Carlos Sainz',
    3: 'Lewis Hamilton',
    4: 'George Russell',
    5: 'Kevin Magnussen',
    6: 'Valtteri Bottas',
    7: 'Esteban Ocon',
    8: 'Yuki Tsunoda',
    9: 'Fernando Alonso',
    10: 'Guanyu Zhou',
    11: 'Mick Schumacher',
    12: 'Lance Stroll',
    13: 'Alexander Albon',
    14: 'Daniel Ricciardo',
    15: 'Lando Norris',
    16: 'Nicholas Latifi',
    17: 'Nico Hulkenberg',
    18: 'Sergio Perez',
    19: 'Max Verstappen',
    20: 'Pierre Gasly',
    21: 'Sebastian Vettel',
    22: 'Nyck De Vries',
    23: 'Logan Sargeant',
    24: 'Oscar Piastri',
    25: 'Liam Lawson',
    26: 'Oliver Bearman',
    27: 'Franco Colapinto',
    28: 'Jack Doohan',
    30: 'Gabriel Bortoleto',
    31: 'Isack Hadjar',
    32: 'Kimi Antonelli'
}

driver_ids = {
    'Charles Leclerc': 1,
    'Carlos Sainz': 2,
    'Lewis Hamilton': 3,
    'George Russell': 4,
    'Kevin Magnussen': 5,
    'Valtteri Bottas': 6,
    'Esteban Ocon': 7,
    'Yuki Tsunoda': 8,
    'Fernando Alonso': 9,
    'Guanyu Zhou': 10,
    'Mick Schumacher': 11,
    'Lance Stroll': 12,
    'Alexander Albon': 13,
    'Daniel Ricciardo': 14,
    'Lando Norris': 15,
    'Nicholas Latifi': 16,
    'Nico Hulkenberg': 17,
    'Sergio Perez': 18,
    'Max Verstappen': 19,
    'Pierre Gasly': 20,
    'Sebastian Vettel': 21,
    'Nyck De Vries': 22,
    'Logan Sargeant': 23,
    'Oscar Piastri': 24,
    'Liam Lawson': 25,
    'Oliver Bearman': 26,
    'Franco Colapinto': 27,
    'Jack Doohan': 28,  
    'Gabriel Bortoleto': 30,
    'Isack Hadjar': 31,
    'Kimi Antonelli': 32
}

track_ids = {
    'Sakhir': 1,
    'Jeddah': 2,
    'Melbourne': 3,
    'Imola': 4,
    'Miami': 5,
    'Barcelona': 6,
    'Monaco': 7,
    'Baku': 8,
    'Montreal': 9,
    'Silverstone': 10,
    'Spielberg': 11,
    'Le Castellet': 12,
    'Budapest': 13,
    'Spa-Francorchamps': 14,
    'Zandvoort': 15,
    'Monza': 16,
    'Marina Bay': 17,
    'Suzuka': 18,
    'Austin': 19,
    'Mexico City': 20,
    'Sao Paulo': 21,
    'Yas Island': 22,
    'Lusail': 23,
    'Las Vegas': 24,
    'Shanghai': 25
}

track_names = {
    1: 'Sakhir',
    2: 'Jeddah',
    3: 'Melbourne',
    4: 'Imola',
    5: 'Miami',
    6: 'Barcelona',
    7: 'Monaco',
    8: 'Baku',
    9: 'Montreal',
    10: 'Silverstone',
    11: 'Spielberg',
    12: 'Le Castellet',
    13: 'Budapest',
    14: 'Spa-Francorchamps',
    15: 'Zandvoort',
    16: 'Monza',
    17: 'Marina Bay',
    18: 'Suzuka',
    19: 'Austin',
    20: 'Mexico City',
    21: 'Sao Paulo',
    22: 'Yas Island',
    23: 'Lusail',
    24: 'Las Vegas',
    25: 'Shanghai'
}


t = {}

for temp in track_ids:
    t[track_ids[temp]] = temp

print(t)